post_install() {
	systemctl enable --now mullvad-daemon
}

pre_upgrade() {
	systemctl stop mullvad-daemon
	
	rm -f /var/cache/mullvad-vpn/relays.json
}

post_upgrade() {
	systemctl daemon-reload
	systemctl start mullvad-daemon
}

pre_remove() {
	systemctl stop mullvad-daemon
	systemctl disable mullvad-daemon
}

post_remove() {
	# remove logs & cache
	rm -rf /var/log/mullvad-vpn/
  	rm -rf /var/cache/mullvad-vpn/
	
	# remove config
	rm -rf /etc/mullvad-vpn
}

