msg() {
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
GREEN="${BOLD}\e[1;32m"
local mesg=$1; shift
printf "
${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" "$@" >&2
}

post_install() {
ln -sf "/usr/share/icons/Paper-Maia/32x32" "/usr/share/icons/Paper-Maia/16x16@2x"
ln -sf "/usr/share/icons/Paper-Maia/48x48" "/usr/share/icons/Paper-Maia/24x24@2x"
msg "Creating paper-maia-mono-dark from paper-mono-dark..."
mkdir "/usr/share/icons/Paper-Maia-Mono-Dark"
ln -sfv "/usr/share/icons/Paper-Mono-Dark/22x22" "/usr/share/icons/Paper-Maia-Mono-Dark/"
ln -sfv "/usr/share/icons/Paper-Mono-Dark/24x24" "/usr/share/icons/Paper-Maia-Mono-Dark"
cp "/usr/share/icons/Paper-Mono-Dark/icon-theme.cache" "/usr/share/icons/Paper-Maia-Mono-Dark/"
cp "/usr/share/icons/Paper-Mono-Dark/index.theme" "/usr/share/icons/Paper-Maia-Mono-Dark/"
if [ -e /usr/share/icons/Paper-Maia-Mono-Dark ]; then sed 's_Paper_Paper-Maia_' -i "/usr/share/icons/Paper-Maia-Mono-Dark/index.theme";
fi
}

post_upgrade() {
  post_install
}

pre_remove() {
rm "/usr/share/icons/Paper-Maia/16x16@2x"
rm "/usr/share/icons/Paper-Maia/24x24@2x"
rm -R "/usr/share/icons/Paper-Maia-Mono-Dark"
}
