post_install() {
	systemctl enable --now nvme0-temp
    echo ---------------------------------------------------------------------------------
	echo 'You can see the temperature with:'
	echo ''
	echo 'cat /tmp/nvme0-temp'
	echo '33'
	echo ''
	echo 'You need something like this in your .conkyrc file to display the temperature:'
	echo ''
	echo '${tail /tmp/nvme0-temp 1 1}°C'
	echo ''
	echo 'or Fahrenheit:'
	echo ''
	echo '${execi 60 echo $(($(cat /tmp/nvme0-temp) * 9 / 5 + 32))}°F'
    echo ---------------------------------------------------------------------------------
}

post_upgrade() {
	systemctl daemon-reload
	systemctl restart nvme0-temp
	
    echo -------------------------------------------------------------
    echo 'nvme0-temp has been restarted.'
    echo -------------------------------------------------------------
}

pre_remove() {
    systemctl disable --now nvme-temp
    
    echo -------------------------------------------------------------
    echo 'nvme0-temp has been stopped & removed.'
    echo -------------------------------------------------------------
}
