post_install() {
	echo -e "****************************************************"
	echo -e "*                                                  *"
	echo -e "* Symlink the games folder to your Home directory: *"
	echo -e "* ln -s /opt/ialauncher/games ~/games              *"
	echo -e "*                                                  *"
	echo -e "****************************************************"
	echo -e -n ""
}

