post_install() {
  echo ""
  echo "To force Libadwaita appliations to use the gtk-4.0 theme,"
  echo "symlink the gtk-4.0 theme to config folder"
  echo "(replace Layan-Dark with chosen theme variant):"
  echo ""
  echo "mkdir -p ~/.config/gtk-4.0/"
  echo "ln -sf /usr/share/themes/Layan-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/"
  echo ""
}

post_upgrade() {
   post_install
}
