post_install() {
    echo -------------------------------------------------------------
    echo 'Start & enable the mullvad-daemon:'
	echo 'systemctl enable --now mullvad-daemon'
    echo -------------------------------------------------------------
}

post_upgrade() {
    systemctl daemon-reload
    systemctl restart mullvad-daemon

    echo -------------------------------------------------------------
    echo 'mullvad-daemon has been restarted.'
    echo -------------------------------------------------------------
}

pre_remove() {
    systemctl disable --now mullvad-daemon
    
    echo -------------------------------------------------------------
    echo 'mullvad-daemon has been stopped & removed.'
    echo -------------------------------------------------------------
}

post_remove() {
    # Remove logs & cache
    rm -rf /var/log/mullvad-vpn/
    rm -rf /var/cache/mullvad-vpn/
}
